-- Create ucimsa database
CREATE ROLE ucimsa WITH LOGIN NOSUPERUSER NOINHERIT NOCREATEDB NOCREATEROLE NOREPLICATION ENCRYPTED PASSWORD 'EMAe6trpN7Q7gu';
REVOKE ALL on DATABASE postgres from ucimsa;
CREATE DATABASE ucimsa WITH OWNER = ucimsa ENCODING = 'UTF8' TABLESPACE = pg_default CONNECTION LIMIT = -1;
